#! /usr/bin/python3

import sys

obracena_pismena = {
    'a': 'ɐ', 'b': 'q', 'c': 'ɔ', 'd': 'p', 'e': 'ǝ', 'f': 'ɟ', 'g': 'ƃ',
    'h': 'ɥ', 'i': 'ᴉ', 'j': 'ɾ', 'k': 'ʞ', 'l': 'l', 'm': 'ɯ', 'n': 'u',
    'o': 'o', 'p': 'd', 'q': 'b', 'r': 'ɹ', 's': 's', 't': 'ʇ', 'u': 'n',
    'v': 'ʌ', 'w': 'ʍ', 'x': 'x', 'y': 'ʎ', 'z': 'z', 'A': '∀', 'B': 'B',
    'C': 'Ɔ', 'D': 'D', 'E': 'Ǝ', 'F': 'Ⅎ', 'G': 'פ', 'H': 'H', 'I': 'I',
    'J': 'ſ', 'K': 'ʞ', 'L': '˥', 'M': 'W', 'N': 'N', 'O': 'O', 'P': 'Ԁ',
    'Q': 'Q', 'R': 'R', 'S': 'S', 'T': '┴', 'U': '∩', 'V': 'Λ', 'W': 'M',
    'X': 'X', 'Y': '⅄', 'Z': 'Z', '0': '0', '1': 'Ɩ', '2': 'ᄅ', '3': 'Ɛ',
    '4': 'ㄣ', '5': 'ϛ', '6': '9', '7': 'ㄥ', '8': '8', '9': '6', ',': "'",
    '.': '˙', '?': '¿', '!': '¡', '"': '„', "'": ',', '`': ',', '(': ')',
    ')': '(', '[': ']', ']': '[', '{': '}', '}': '{', '<': '>', '>': '<',
    '&': '⅋', '_': '‾',
}

# def obrat(text):
 #   return ''.join(obracena_pismena.get(c, c) for c in reversed(text))
   
# print(obrat(obracena_pismena))
exit_code = 0

def otoc(vstup):
    global exit_code  
    vysledek = ''
    for znak in vstup:
        if znak in obracena_pismena:
            hodnota = obracena_pismena[znak]
        elif znak == "\n" or  znak == " ":
            hodnota = ""
        else:
            hodnota = znak
            if exit_code != 2:
                exit_code = 2
        vysledek =   hodnota + vysledek 
    return  vysledek.strip(), exit_code

def chybovy_vystup():
    if exit_code == 0:
        exit(0)
    elif exit_code == 2:
        exit(2)

soubory = []
for arg in sys.argv[1:]:
    if arg == "-":
        soubory.append("-")
    elif arg == "--help":
        soubory.append("--help")
        exit(f"Zadat lze - nebo dokument jménem .txt")
    elif arg.startswith("-"):
        #sys.stderr.write("Přepínač ")
        #sys.stderr.write(soubor)s
        #sys.stderr.write(" neexistuje viz --help")
        #sys.stderr.write(x)
        sys.exit(f"Přepínač {arg}  neexistuje viz --help") 
    else:
        soubory.append(arg)
        
if soubory == []:    
    vstup = sys.stdin.read()
    vysledek, exit_code = otoc(vstup)
    print(vysledek)
    x=chybovy_vystup()
                      
for soubor in soubory:
    if soubor == "-":
        vstup = sys.stdin.read()
        vysledek, exit_code = otoc(vstup)
        print(vysledek)
        x=chybovy_vystup()             
    else:    
        with open (soubor, encoding="utf-8") as s:
            text = s.readlines()
            for vstup in text:
                vysledek, exit_code = otoc(vstup)
                print(vysledek)
            chybovy_vystup()
                














